# FLAGS
TIME_FLAG = True

SAVE_DESCRIPTORS = False
READ_DESCRIPTORS = False
DRAW = False


# PARAMETERS
SAMPLE_RATE = 10
FRAME_RESIZE = (72,40)
ORIENTATION_THRESHOLD = 20
N_NEIGHBORS = 3
# por el momento solo uso el mejor vecino

#DETECTION PARAMETERS
INTERVALO_PENDIENTE = (0.88,1.11)
THRESHOLD = 0.6